### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by robbyjuice** [msubhash/fuzzywuzzy-java#3]
Hi msubhash, 

I really like this java port of fuzzywuzzy and I'd like to use it on my project. However, I was curious about the license status of this code - is this code currently licensed under any license? If not, could you release it under the license that the original fuzzywuzzy was released under (MIT)? 

Thanks!

**Comment by msubhash** [comment]
I will release it under MIT license. Thanks for notifying me.

**Comment by msubhash** [comment]
I will add the license.

**Comment by robbyjuice** [comment]
Thank you!
